name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
      tags:
          description: 'Manual trigger' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  
  unit-tests:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Setting Default Timezone
      uses: szenius/set-timezone@v1.0  
    - name: Checking out
      uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Unit tests
      run: ./gradlew test 
      
  android-tests:
  
    runs-on: macos-latest
    
    steps:
    - name: Setting Default Timezone
      uses: szenius/set-timezone@v1.0  
    - name: Checking out    
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 26
        script: ./gradlew connectedAndroidTest
